---
- name: install jq
  tags: backup
  apt:
    name: jq
    update_cache: yes

- name: create sensor-wiki-backup bash script
  tags: backup
  template:
    dest: /usr/local/bin/sensor-wiki-backup.sh
    owner: root
    mode: "0700"
    src: sensor-wiki-backup-bash.j2

- name: create sensor-wiki-backup systemd timer file
  tags: backup
  template:
    dest: /etc/systemd/system/sensor-wiki-backup.timer
    owner: root
    src: sensor-wiki-backup-timer.j2

- name: copy sensor-wiki-backup systemd unit file
  tags: backup
  copy:
    dest: /etc/systemd/system/sensor-wiki-backup.service
    owner: root
    src: sensor-wiki-backup.service

- name: start and enable mongobackup timer
  tags: backup
  systemd:
    name: sensor-wiki-backup.timer
    enabled: yes
    daemon_reload: yes
    state: started
