---
- hosts: all
  gather_facts: False
  become: yes

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: all
  become: yes
  pre_tasks:
    - name: apt-get update + upgrade
      apt:
        upgrade: dist

  roles:
    - geerlingguy.ntp
    - tersmitten.swapfile

- hosts: mongodb
  remote_user: ubuntu
  become: yes
  pre_tasks:
    - name: set mongodb_conf_bind_ip to internal ip
      set_fact:
        mongodb_conf_bind_ip: "{{ ansible_eth0.ipv4.address }}"
    - name: create partition
      shell:  echo -e "o\nn\np\n1\n\n\nw" | fdisk {{ xfs_disk }} && touch /partition_created
      args:
        creates: /partition_created
    - name: create xfs
      filesystem:
        fstype: xfs
        dev: "{{ xfs_disk }}1"
    - name: mount xfs disk
      mount:
        state: mounted
        fstype: xfs
        opts: defaults,noatime,discard
        src: "{{ xfs_disk }}1"
        name: "{{ xfs_disk_mountpoint }}"
        dump: 0
        passno: 0
    - name: create systemd unit file for configuring transparent hugepages
      copy:
        dest: /etc/systemd/system/disable-transparent-huge-pages.service
        owner: root
        src: ./files/disable-transparent-huge-pages.service
    - name: run systemd unit file for configuring transparent hugepages
      systemd:
        name: disable-transparent-huge-pages
        daemon_reload: yes
        enabled: yes
        state: started
    - name: create systemd unit file for setting readahead to 0 for {{ xfs_disk }}
      template:
        dest: /etc/systemd/system/set-readahead.service
        owner: root
        src: ./files/set-readahead.service.j2
    - name: run systemd unit file for setting readahead to 0 for {{ xfs_disk }}
      systemd:
        name: set-readahead
        daemon_reload: yes
        enabled: yes
        state: started

  post_tasks:
    - name: create mongodb_keyfile
      copy:
        dest: /etc/mongodb_keyfile
        src: ./files/mongodb_keyfile
        owner: mongodb
        mode: 0400
    - name: overwrite mongod systemd unit file with optimized unit file
      copy:
        dest: /etc/systemd/system/mongod.service
        src: ./files/optimized-mongod.service
        owner: root
    - name: set tcp keepalive to 120
      sysctl:
        name: net.ipv4.tcp_keepalive_time
        value: 120
    - name: add keyfile option to /etc/mongod.conf
      blockinfile:
        name: /etc/mongod.conf
        block: |
          keyFile = /etc/mongodb_keyfile
    - name: set TZ env variable in /etc/environment
      blockinfile:
        name: /etc/environment
        block: |
          TZ=:/etc/localtime
    - name: restart mongod service
      systemd:
        name: mongod
        daemon_reload: yes
        enabled: yes
        state: restarted

  roles:
  - Stouts.mongodb

